In [4]:
import numpy as np 
data=np.random.randn(2,3)
print(data)
print(data*10)
print(data+data)

[[ 0.5057775   0.26668301 -1.46002594]
 [-0.29780257  0.57649309 -0.55434999]]
[[  5.05777495   2.66683013 -14.60025939]
 [ -2.97802568   5.76493091  -5.54349988]]
[[ 1.01155499  0.53336603 -2.92005188]
 [-0.59560514  1.15298618 -1.10869998]]


In [5]:
data1=[6, 7.5, 8, 0, 1]
arr1=np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [6]:
data2= [[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)



[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr3=np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr4=np.ones((2,3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr5=np.empty((2,3))
print(arr5)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arr6=np.arange(5)
print(arr6)

[0 1 2 3 4]


In [11]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
print(arr)
arr2=arr*arr
print(arr2)
arr2=1/arr
print(arr2)
arr2=np.array([[0., 4., 1.],[7., 2., 12.]])
val= arr2>arr
print(val)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[False  True False]
 [ True False  True]]


In [12]:
arr=np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8]=12
print(arr)
arr[:]=10
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[10 10 10 10 10 10 10 10 10 10]


In [13]:
arr2d=np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
arr2d[0][2]
arr2d[0, 2]

[7 8 9]


3

In [14]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr3d)
print(arr3d[0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]


In [15]:
old=arr3d[0].copy()
print(old)
print(arr3d[1,0])

[[1 2 3]
 [4 5 6]]
[7 8 9]


In [16]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4) #generate normal distribution
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.53595221 -0.50273306  0.06796658 -1.16182778]
 [ 0.95393428  1.00349433  1.47397301 -1.86126355]
 [-0.76626744 -0.45737911 -0.44137742  1.6373185 ]
 [-0.44917349 -0.60397389  0.07806457  0.89595346]
 [-1.28794282  0.96422626 -0.75779441 -0.08820014]
 [-0.37022912 -1.65966267 -0.05073863 -1.40480442]
 [ 1.34241423  0.18151904  1.26638988 -0.38431956]]


In [17]:
print(names == "Bob") # Comparison operation

[ True False False  True False False False]


In [18]:
print(data[names == "Bob"])

[[-1.53595221 -0.50273306  0.06796658 -1.16182778]
 [-0.44917349 -0.60397389  0.07806457  0.89595346]]


In [19]:
mask = (names == "Bob") | (names == "Will")
print(mask)

[ True False  True  True  True False False]


In [20]:
print(data[mask])

[[-1.53595221 -0.50273306  0.06796658 -1.16182778]
 [-0.76626744 -0.45737911 -0.44137742  1.6373185 ]
 [-0.44917349 -0.60397389  0.07806457  0.89595346]
 [-1.28794282  0.96422626 -0.75779441 -0.08820014]]


In [21]:
arr = np.empty((8, 4))
for i in range(8):
  arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [22]:
print(arr[[4,3,0,6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [23]:
arr = np.arange(32).reshape((8, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [24]:
1. # (1,0), (5, 3), (7, 1), (2, 2)
print(arr[[1,5,7,2],[0,3,1,2]])

[ 4 23 29 10]


In [25]:
arr = np.arange(15).reshape((3, 5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [26]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [27]:
arr = np.random.randn(6, 3)
print(arr)

[[-0.52579218  0.37132884  0.77103157]
 [-0.14537895  0.47095767  1.73289133]
 [-2.79519798 -1.16349077  0.39254039]
 [-0.9994651   0.15711999  1.34794223]
 [ 0.48388087 -0.47178847 -1.57114172]
 [-1.50305462  0.79010818 -1.14398518]]


In [28]:
val = np.dot(arr.T, arr)
print(val)

[[11.60296859  1.41557681 -2.14255081]
 [ 1.41557681  2.58493899  0.69487077]
 [-2.14255081  0.69487077  9.34562665]]


In [29]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [31]:
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [32]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)

[-0.0292323   0.77182507  0.12256621  0.19880546 -0.3531034  -0.90141654
  0.05257661  1.70365081]


In [33]:
print(y)

[ 0.86703117  1.05397549  0.31994079 -0.03984614  0.19754473  1.41567743
 -0.58410374  0.10389041]


In [34]:
val = np.maximum(x, y)
print(val)

[0.86703117 1.05397549 0.31994079 0.19880546 0.19754473 1.41567743
 0.05257661 1.70365081]


In [35]:
arr = np.random.randn(7) * 5
print(arr)

[-2.59457188 -1.85004475  0.32886664  1.84964636 -2.30298526 -1.90453271
 -1.54143961]


In [36]:
remainder, whole_part = np.modf(arr)
print(remainder)

[-0.59457188 -0.85004475  0.32886664  0.84964636 -0.30298526 -0.90453271
 -0.54143961]


In [37]:
print(whole_part)

[-2. -1.  0.  1. -2. -1. -1.]


In [47]:
arr=np.arange(0,9)
print(arr)

[0 1 2 3 4 5 6 7 8]
